# Generated by Django 5.0.2 on 2024-02-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, verbose_name='Task Name')),
                ('email_list', models.TextField(verbose_name='Email List')),
                ('email_subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('email_body', models.TextField(verbose_name='Email Body')),
                ('email_file', models.FileField(upload_to='media/', verbose_name='Email File')),
            ],
        ),
    ]
